import com.android.build.api.dsl.LibraryExtension
import org.gradle.accessors.dm.LibrariesForLibs
import org.gradle.kotlin.dsl.the
import org.jetbrains.dokka.gradle.formats.DokkaFormatPlugin
import org.jetbrains.dokka.gradle.internal.InternalDokkaGradlePluginApi
import org.jetbrains.kotlin.gradle.dsl.JvmTarget
import org.jetbrains.kotlin.gradle.tasks.KotlinCompilationTask

plugins {
    id("com.android.library")
    id("org.jetbrains.dokka")
    id("org.owasp.dependencycheck")
    id("org.sonarqube")
    id("org.jetbrains.kotlinx.kover")
}

val libs = the<LibrariesForLibs>()
val NAMESPACE: String by project
val GROUP: String by project
val POM_DESCRIPTION: String by project

group = GROUP
version = providers.gradleProperty("VERSION_NAME").get()

extensions.configure<LibraryExtension> {
    namespace = NAMESPACE
    compileSdk = 35

    defaultConfig {
        minSdk = 26
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        testApplicationId = "$NAMESPACE.test"
        testHandleProfiling = true
        testFunctionalTest = true
        consumerProguardFiles("consumer-rules.pro")
    }

    buildTypes {
        getByName("debug") {
            enableUnitTestCoverage = true
            enableAndroidTestCoverage = false
        }
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
        targetCompatibility = JavaVersion.toVersion(libs.versions.java.get())
    }

    packaging {
        resources {
            excludes += listOf("/META-INF/{AL2.0,LGPL2.1}")
            excludes += listOf("/META-INF/versions/9/OSGI-INF/MANIFEST.MF")
        }
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }

    publishing {
        singleVariant("release") {
            withSourcesJar()
        }
    }
}

tasks.withType<KotlinCompilationTask<*>>().configureEach {
    compilerOptions {
        if (this is org.jetbrains.kotlin.gradle.dsl.KotlinJvmCompilerOptions) {
            jvmTarget.set(JvmTarget.fromTarget(libs.versions.java.get()))
        }
        freeCompilerArgs.addAll(
            "-opt-in=kotlin.RequiresOptIn",
            "-opt-in=kotlin.time.ExperimentalTime"
        )
    }
}

dependencyCheck {
    formats = listOf("XML", "HTML")
    nvd.apiKey = System.getenv("NVD_API_KEY") ?: providers.gradleProperty("nvdApiKey").orNull ?: ""
    nvd.delay = 10000
    nvd.maxRetryCount = 2
}

// Dokka 2.x — apply GFM (markdown) format plugin and configure output per module
@OptIn(InternalDokkaGradlePluginApi::class)
abstract class DokkaMarkdownPlugin : DokkaFormatPlugin(formatName = "markdown") {
    override fun DokkaFormatPlugin.DokkaFormatPluginContext.configure() {
        project.dependencies {
            dokkaPlugin(dokka("gfm-plugin"))
            formatDependencies.dokkaPublicationPluginClasspathApiOnly
                .dependencies.addLater(dokka("gfm-template-processing-plugin"))
        }
    }
}
apply<DokkaMarkdownPlugin>()

dokka {
    moduleName.set(project.name)
    dokkaPublications.named("markdown") {
        outputDirectory.set(file("$projectDir/docs"))
    }
}

tasks.named("dokkaGeneratePublicationMarkdown").configure {
    doFirst { delete(file("$projectDir/docs")) }
}

tasks.named("dokkaGenerateMarkdown") {
    group = "documentation"
}

tasks.register<Jar>("dokkaHtmlJar") {
    group = "documentation"
    dependsOn("dokkaGeneratePublicationHtml")
    from(tasks.named("dokkaGeneratePublicationHtml"))
    archiveClassifier.set("html-docs")
    description = "Assembles a JAR containing the HTML documentation generated by Dokka."
}

// Disable AGP's javaDocReleaseGeneration (it hits a "PermittedSubclasses requires ASM9"
// error on this codebase) and replace the javadoc.jar contents with Dokka's HTML output.
afterEvaluate {
    tasks.findByName("javaDocReleaseGeneration")?.enabled = false
    tasks.findByName("javaDocReleaseJar")?.let { task ->
        if (task is Jar) {
            task.from(tasks.named("dokkaGeneratePublicationHtml"))
            task.dependsOn("dokkaGeneratePublicationHtml")
        }
    }
}
